---
# - -
- name: Set up Docker on host
  hosts: all
  roles:
    - docker

- name: Setting up Rancher Server
  hosts: "rancher"
  roles:
    - { role: rancher, tags: ["rancher"] }
  
- name: Register Rancher Hosts
  hosts: "nodes"
  roles:
    - { role: rancher_reg, tags: ["rancher_reg"] }

#- name: Create api key
#  hosts: all
#  roles:
#    - { role: rancher_api, tags: ["rancher_api"] }
