---
- name: Create api
  command: ./api.sh
  register: rancher_api_output
  until: rancher_api_output.stdout.find("publicValue") != -1
  retries: 30
  delay: 10

- debug:
    msg: "{{ rancher_api_output.stdout|from_json }}"

- debug: 
    msg: "{{ (rancher_api_output.stdout|from_json).publicValue }}" 

- debug: 
    msg: "{{ (rancher_api_output.stdout|from_json).secretValue }}" 

- name: Get ec2 information
  action: uri
      method=GET
      status_code=200
      url="http://169.254.169.254/latest/dynamic/instance-identity/document" return_content=yes
  register: ec2_info

- debug:
    msg: "{{ ec2_info.content|from_json }}"

- name: trigger lambda    
  uri: 
    url: "{{ lookup('env','lambda_url') }}"
    method: POST
    return_content: yes
    HEADER_Content-Type: "application/json"
    body: {"publicValue":"{{ (rancher_api_output.stdout|from_json).publicValue }}","secretValue":"{{ (rancher_api_output.stdout|from_json).secretValue }}","instance_ip":"{{ (ec2_info.content|from_json).privateIp }}","instance_id":"{{ (ec2_info.content|from_json).instanceId }}"}